### ISSUE TITLE
Неплохо бы в сервисы добавить сразу Postgres

### ISSUE THREAD

**Issue by coursar** [Desire456/spring-course-4#3]
https://github.com/Desire456/spring-course-4/blob/29f97e5b70cf8ef3d3bf0b412625422c37126d04/docker-compose.yml#L1

**Comment by coursar** [comment]
И инициализировать заодно

**Comment by Desire456** [comment]
Неплохо, я согласен. Но я через локальный постгрес тестировал, поэтому не написал. Все issue закрыл
