### ISSUE TITLE
Оне не создавать их должен, а получать с сервиса пользователей

### ISSUE THREAD

**Issue by coursar** [Desire456/spring-course-4#4]
https://github.com/Desire456/spring-course-4/blob/29f97e5b70cf8ef3d3bf0b412625422c37126d04/aggregator/src/main/java/com/example/aggregator/controller/PaymentController.java#L25-L29

**Comment by Desire456** [comment]
а кто тогда скажет создавать сервису пользователей? или вы имеете ввиду, что нужно просить от сервиса пользователей просто пользователей по гет запросу, а то что он там внутри делает (создает/достает из базы уже часть готовых/другое) уже не важно?

**Comment by coursar** [comment]
Всё верно - создавайте их через ApplicationRunner или docker-entrypoint-initdb.d, главное - они у вас изначально есть (это не дело сервиса проведения платежей создавать юзеров).
